[features]
resolution = true
skip-lint = false

[programs.localnet]
axiom_id = "AXioMprgrm111111111111111111111111111111111"
agent_soul_factory = "AXioMsoul1111111111111111111111111111111111"
axiom_attestations = "AXiomAtst1111111111111111111111111111111111"
axiom_staking = "AXiomStk1111111111111111111111111111111111"
axiom_token = "AXiomTok1111111111111111111111111111111111"
axiom_governance = "AXiomGov1111111111111111111111111111111111"
axiom_pohw = "AXiomPoHWProg111111111111111111111111111111"
axiom_staking_dynamic = "AXiomStkD111111111111111111111111111111111"

[programs.devnet]
axiom_id = "AXioMprgrm111111111111111111111111111111111"
agent_soul_factory = "AXioMsoul1111111111111111111111111111111111"
axiom_attestations = "AXiomAtst1111111111111111111111111111111111"
axiom_staking = "AXiomStk1111111111111111111111111111111111"
axiom_token = "AXiomTok1111111111111111111111111111111111"
axiom_governance = "AXiomGov1111111111111111111111111111111111"
axiom_pohw = "AXiomPoHWProg111111111111111111111111111111"
axiom_staking_dynamic = "AXiomStkD111111111111111111111111111111111"

[programs.mainnet]
axiom_id = "AXioMprgrm111111111111111111111111111111111"
agent_soul_factory = "AXioMsoul1111111111111111111111111111111111"
axiom_attestations = "AXiomAtst1111111111111111111111111111111111"
axiom_staking = "AXiomStk1111111111111111111111111111111111"
axiom_token = "AXiomTok1111111111111111111111111111111111"
axiom_governance = "AXiomGov1111111111111111111111111111111111"
axiom_pohw = "AXiomPoHWProg111111111111111111111111111111"
axiom_staking_dynamic = "AXiomStkD111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"